language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy
#   - pypy3
#   pending release of a fix for https://bitbucket.org/pypy/pypy/issue/1946
install:
    - pip install .
script:
    - python setup.py test -q
notifications:
    email: false
